inherit_gem:
  rubocop-shopify: rubocop.yml

require:
- rubocop-rake
- rubocop-minitest
- rubocop-sorbet

AllCops:
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  NewCops: enable

Sorbet/ValidSigil:
  MinimumStrictness: true
  Enabled: true
  Exclude:
    - "bench/**/*.rb"
    - "rakelib/**/*.rake"

Sorbet/FalseSigil:
  Enabled: false

Sorbet/StrictSigil:
  Enabled: true
  Exclude:
    - "test/**/*.rb"
    - "bench/**/*.rb"
    - "rakelib/**/*.rake"

Sorbet/ConstantsFromStrings:
  Enabled: false
